AWSTemplateFormatVersion: 2010-09-09
Description: Resume Book API Lambda
Transform: AWS::Serverless-2016-10-31

Parameters:
  LambdaFunctionName:
    Type: String
    AllowedPattern: ^[a-zA-Z0-9]+[a-zA-Z0-9-]+[a-zA-Z0-9]+$
    Default: infra-resume-book-api-lambda

  S3Bucket:
    Type: String
    Default: acm-uiuc-code

  ApiSpecS3Key:
    Type: String
    Default: swagger-resume-book.yml
  

Resources:
  ResumeBookApiLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../code 
      AutoPublishAlias: live
      Runtime: python3.10
      Description: Resume Book API Lambda
      FunctionName: !Ref LambdaFunctionName
      Handler: api.lambda_handler
      MemorySize: 2048
      Role: !GetAtt ResumeBookApiLambdaIAMRole.Arn
      Timeout: 60

  ResumeBookApiLambdaIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${LambdaFunctionName}:*
          PolicyName: lambda

  ResumeBookApiLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${LambdaFunctionName}
      RetentionInDays: 7

  ResumeBookApiGateway:
    Type: AWS::ApiGateway::RestApi
    DependsOn: 
      - ResumeBookApiLambdaFunction
    Properties:
      Name: infra-resume-book-api-gw
      BodyS3Location:
        Bucket: !Ref S3Bucket
        Key: !Ref ApiSpecS3Key


  ResumeBookApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref ResumeBookApiGateway

  ResumeBookApiStage:
    Type: AWS::ApiGateway::Stage
    DependsOn:
      - ResumeBookApiGatewayDeployment
    Properties:
      DeploymentId: !Ref ResumeBookApiGatewayDeployment
      RestApiId: !Ref ResumeBookApiGateway
      StageName: default

  ResumeBookLambdaApiGatewayHealthz:
    Type: AWS::Lambda::Permission
    DependsOn:
      - ResumeBookApiGateway
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt ResumeBookApiLambdaFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ResumeBookApiGateway}/*/GET/api/v1/healthz

  ResumeBookLambdaApiGatewayStudentUploadURL:
    Type: AWS::Lambda::Permission
    DependsOn:
      - ResumeBookApiGateway
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt ResumeBookApiLambdaFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ResumeBookApiGateway}/*/GET/api/v1/student/getUploadURL

  ResumeBookApiGatewayDomainName:
    Type: 'AWS::ApiGateway::DomainName'
    Properties:
      DomainName: resume-api.acm.illinois.edu
      CertificateArn: >-
        arn:aws:acm:us-east-1:298118738376:certificate/4ba7200a-cfc7-4234-b242-0281030df5f5

  ResumeBookApiMapping:
    Type: 'AWS::ApiGatewayV2::ApiMapping'
    Properties:
      DomainName: resume-api.acm.illinois.edu
      ApiId: !Ref ResumeBookApiGateway
      Stage: !Ref ResumeBookApiStage


Outputs:
  ApiUrl:
    Value: !Sub
      - https://${ApiId}.execute-api.${AWS::Region}.amazonaws.com/${StageName}
      - ApiId: !Ref ResumeBookApiGateway
        StageName: !Ref ResumeBookApiStage