AWSTemplateFormatVersion: 2010-09-09
Description: Resume Book API Lambda
Transform: AWS::Serverless-2016-10-31

Parameters:
  LambdaFunctionName:
    Type: String
    AllowedPattern: ^[a-zA-Z0-9]+[a-zA-Z0-9-]+[a-zA-Z0-9]+$
    Default: infra-resume-book-api-lambda

  AADLambdaFunctionName:
    Type: String
    AllowedPattern: ^[a-zA-Z0-9]+[a-zA-Z0-9-]+[a-zA-Z0-9]+$
    Default: infra-resume-book-aad-auth-lambda

  S3Bucket:
    Type: String
    Default: acm-uiuc-code

  ApiSpecS3Key:
    Type: String
    Default: swagger-resume-book.yml
  

Resources:
  # API Lambda
  ResumeBookApiLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../code 
      AutoPublishAlias: live
      Runtime: python3.10
      Description: Resume Book API Lambda
      FunctionName: !Ref LambdaFunctionName
      Handler: api.lambda_handler
      MemorySize: 2048
      Role: !GetAtt ResumeBookApiLambdaIAMRole.Arn
      Timeout: 60

  ResumeBookApiLambdaIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${LambdaFunctionName}:*
          PolicyName: lambda

  ResumeBookApiLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${LambdaFunctionName}
      RetentionInDays: 7

# AAD Authorizer

  ResumeBookAADLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../code/authorizers/
      AutoPublishAlias: live
      Runtime: python3.10
      Description: Resume Book AAD Auth Lambda
      FunctionName: !Ref AADLambdaFunctionName
      Handler: aad.lambda_handler
      MemorySize: 2048
      Role: !GetAtt ResumeBookAADLambdaIAMRole.Arn
      Timeout: 60
    
  ResumeBookAADLambdaIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - apigateway.amazonaws.com
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AADLambdaFunctionName}:*
          PolicyName: lambda

  ResumeBookAADLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AADLambdaFunctionName}
      RetentionInDays: 7

# API Gateway
  ResumeBookApiGateway:
    Type: AWS::Serverless::Api
    DependsOn: 
      - ResumeBookApiLambdaFunction
    Properties:
      Name: infra-resume-book-api-gw
      Description: Resume Book API Gateway
      AlwaysDeploy: True
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ../docs/swagger-resume-book.yml
      Auth:
        Authorizers:
          AADAuthorizer:
            FunctionArn: !GetAtt ResumeBookAADLambdaFunction.Arn
      Domain: 
        DomainName: resume-api.acm.illinois.edu
        CertificateArn: >-
          arn:aws:acm:us-east-1:298118738376:certificate/4ba7200a-cfc7-4234-b242-0281030df5f5
      StageName: default
    


  AadAuthorizerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt ResumeBookAADLambdaFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ResumeBookApiGateway}/authorizers/*"

  APILambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::GetAtt:
        - ResumeBookApiLambdaFunction
        - Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref AWS::Region
          - ":"
          - !Ref AWS::AccountId
          - ":"
          - !Ref ResumeBookApiGateway
          - "/*/*/*"
  # S3 Bucket
  ResumeStorageS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: infra-resume-book-pdfs
          
Outputs:
  ApiUrl:
    Value: !Sub
      - https://${ApiId}.execute-api.${AWS::Region}.amazonaws.com/default
      - ApiId: !Ref ResumeBookApiGateway
