AWSTemplateFormatVersion: 2010-09-09
Description: Resume Book API - IAM Roles
Transform: AWS::Serverless-2016-10-31


Parameters:
  LambdaFunctionName:
    Type: String
    AllowedPattern: ^[a-zA-Z0-9]+[a-zA-Z0-9-]+[a-zA-Z0-9]+$
  AuthLambdaFunctionName:
    Type: String
    AllowedPattern: ^[a-zA-Z0-9]+[a-zA-Z0-9-]+[a-zA-Z0-9]+$
  LogRetentionDays:
    Type: Number


Resources:
  ResumeBookApiLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${LambdaFunctionName}
      RetentionInDays: !Ref LogRetentionDays

  ResumeBookApiLambdaNoVpcLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${LambdaFunctionName}-novpc
      RetentionInDays: !Ref LogRetentionDays

  ResumeBookAuthLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AuthLambdaFunctionName}
      RetentionInDays: !Ref LogRetentionDays