AWSTemplateFormatVersion: 2010-09-09
Description: Resume Book API Stateful Resources

Parameters:
  ProfileDataTableName:
    Type: String
    AllowedPattern: ^[a-zA-Z0-9]+[a-zA-Z0-9-]+[a-zA-Z0-9]+$
    Default: infra-resume-book-profile-data
  HashKeyElementName:
    Type: String
    Default: username
    Description: User Auth Primary Key Name
  HashKeyElementType:
    Type: String
    Default: S
    Description: User Auth Primary Key Type

Resources:
  ProfileDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref ProfileDataTableName
      AttributeDefinitions:
        - 
          AttributeName: !Ref HashKeyElementName
          AttributeType: !Ref HashKeyElementType
      KeySchema:
        - 
          AttributeName: !Ref HashKeyElementName
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: "project"
          Value: "infra-resume-book"
        - Key: "techlead"
          Value: "jgoon2@illinois.edu"
