name: Deploy Resources to AWS PROD/DEV
run-name: Deploy resources to AWS PROD/DEV by @${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "code/**"
      - "cloudformation/main.yml"
      - "docs/**"
      - "Makefile"
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    concurrency:
      group: resume-book-aws-dev
      cancel-in-progress: false
    environment: "AWS DEV"
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: make deploy_dev
  test-dev:
    runs-on: ubuntu-latest
    needs:
      - deploy-dev
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11 for testing
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Run live testing
        run: make test_ci
  deploy-prod:
    runs-on: ubuntu-latest
    concurrency:
      group: resume-book-aws-prod
      cancel-in-progress: false
    needs:
      - test-dev
      - deploy-dev
    environment: "AWS PROD"
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: make deploy_prod
  health-check-prod:
    runs-on: ubuntu-latest
    needs:
      - deploy-prod
    steps:
      - name: Call the healthz endpoint
        run: curl -f https://resume-api.acm.illinois.edu/api/v1/healthz 

