name: Deploy all resources to DEV
run-name: DEV deploy - @${{ github.actor }}

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  test-unit:
    runs-on: ubuntu-latest
    name: Run Unit Tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11 for testing
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Setup Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Run unit testing
        run: make test_unit
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: resume-book-aws-dev
      cancel-in-progress: false
    environment: "AWS DEV"
    name: Deploy to AWS DEV
    needs:
      - test-unit
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: make deploy_dev
  deploy-cf-pages-dev:
    runs-on: ubuntu-latest
    concurrency:
      group: resume-book-cf-pages-dev
      cancel-in-progress: false
    permissions:
      contents: read
      deployments: write  
    needs:
      - test-unit
    name: Deploy to Cloudflare Pages DEV
    environment: "Cloudflare Pages - Dev"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Build
        run: cd clientv2 && corepack enable && yarn && yarn run build
        env:
          VITE_AAD_CLIENT_ID: 251efa82-f589-42e1-9ebb-e214a4f40a0f
          VITE_API_URL: https://resumes.aws.qa.acmuiuc.org/api/v1
          VITE_KINDE_CLIENT_ID: 9dfcd7977da347f3ab55fbb909a4d5cf
          VITE_RUN_ENVIRONMENT: dev
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: resume-book-dev
          directory: clientv2/dist/
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    name: Run Live Integration Tests
    needs:
      - deploy
      - deploy-cf-pages-dev
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11 for testing
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Setup Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Run live testing
        run: make test_live_integration
        env:
          RB_JWT_SECRET: ${{ secrets.RB_JWT_SECRET }}
      - name: Run E2E testing
        run: make test_e2e
        env:
          RB_PLAYWRIGHT_USERNAME: ${{ secrets.RB_PLAYWRIGHT_USERNAME }}
          RB_PLAYWRIGHT_PASSWORD: ${{ secrets.RB_PLAYWRIGHT_PASSWORD }}
          RB_JWT_SECRET: ${{ secrets.RB_JWT_SECRET }}
          CI: true